import 'dart:async';
import 'tool_interface.dart';
import 'tool_definition.dart';
import 'tool_result.dart';
import '../services/password_service.dart';

/// Password manager: store, retrieve, search, generate passwords.
class ManagePasswordTool implements ToolInterface {
  static const _definition = ToolDefinition(
    name: 'manage_password',
    description:
        'Passwort-Verwaltung: speichern, suchen, anzeigen, generieren, loeschen. '
        'Schuetzt sensible Daten im Android Keystore.',
    parametersSchema: {
      'type': 'object',
      'properties': {
        'action': {
          'type': 'string',
          'enum': ['store', 'search', 'get', 'delete', 'generate', 'list'],
          'description':
              'store=neu speichern, search=name durchsuchen, get=ID anzeigen, '
              'delete=ID loeschen, generate=neues Passwort generieren, list=alle anzeigen',
        },
        'name': {
          'type': 'string',
          'description': 'Name des Eintrags, z.B. "Gmail", "WiFi", "AMS"',
        },
        'username': {'type': 'string', 'description': 'Benutzername (optional)'},
        'password': {
          'type': 'string',
          'description': 'Passwort (optional, fuer store); bei leer wird generate erstellt',
        },
        'url': {'type': 'string', 'description': 'Webseite/App URL (optional)'},
        'notes': {'type': 'string', 'description': 'Notizen (optional)'},
        'id': {'type': 'string', 'description': 'Eintrags-ID fuer get/delete'},
        'query': {'type': 'string', 'description': 'Suchbegriff fuer action=search'},
        'length': {
          'type': 'integer',
          'description': 'Passwort-Laenge fuer generate (default 20)',
        },
      },
      'required': ['action'],
    },
  );

  @override
  ToolDefinition get definition => _definition;

  /// Callbacks injected by main.dart
  static PasswordService? passwordService;

  @override
  Future<ToolResult> execute(Map<String, dynamic> parameters) async {
    final action = (parameters['action'] as String?)?.toLowerCase() ?? '';

    if (passwordService == null) {
      return ToolResult(
        toolName: definition.name,
        parameters: parameters,
        result: 'Fehler: Passwort-Service nicht verfuegbar.',
        displayText: '❌ Passwort-Manager nicht initialisiert',
        isError: true,
      );
    }

    switch (action) {
      case 'store':
        return await _store(parameters);
      case 'search':
        return await _search(parameters);
      case 'get':
        return await _get(parameters);
      case 'delete':
        return await _delete(parameters);
      case 'generate':
        return _generate(parameters);
      case 'list':
        return await _list();
      default:
        return ToolResult(
          toolName: definition.name,
          parameters: parameters,
          result: 'Unbekannte Aktion: $action',
          displayText: '❓ Aktion nicht erkannt',
        );
    }
  }

  Future<ToolResult> _store(Map<String, dynamic> p) async {
    final nameEntry = (p['name'] as String?)?.trim() ?? '';
    if (nameEntry.isEmpty) {
      return ToolResult(
        toolName: definition.name,
        parameters: p,
        result: '{"error": "name required for store"}',
        displayText: '❌ Name fehlt',
        isError: true,
      );
    }

    String? pw = (p['password'] as String?)?.trim();
    final bool autoGen = pw == null || pw.isEmpty;
    if (autoGen) {
      pw = PasswordService.generatePassword(length: p['length'] as int? ?? 20);
    }

    final entry = await passwordService!.createEntry(
      name: nameEntry,
      username: (p['username'] as String?)?.trim(),
      password: pw,
      url: (p['url'] as String?)?.trim(),
      notes: (p['notes'] as String?)?.trim(),
    );

    final strength = PasswordService.checkStrength(pw);
    return ToolResult(
      toolName: definition.name,
      parameters: p,
      result: '{"id": "${entry.id}", "name": "${entry.name}", "autoGenerated": $autoGen, "strength": "${strength.label}"}',
      displayText:
          '🔐 "${entry.name}" gespeichert. ${autoGen ? 'Passwort generiert (${strength.label}).' : ''}',
    );
  }

  Future<ToolResult> _search(Map<String, dynamic> p) async {
    final query = (p['query'] as String?)?.trim() ?? '';
    if (query.isEmpty) {
      return ToolResult(
        toolName: definition.name,
        parameters: p,
        result: '{"error": "query required for search"}',
        displayText: '❌ Suchbegriff fehlt',
        isError: true,
      );
    }
    final results = await passwordService!.search(query);
    if (results.isEmpty) {
      return ToolResult(
        toolName: definition.name,
        parameters: p,
        result: '{"found": []}',
        displayText: '🔍 Keine Passwoerter fuer "$query" gefunden',
      );
    }

    final jsonParts = <String>[];
    final lines = <String>[];
    for (final e in results) {
      final s = e.password != null ? PasswordService.checkStrength(e.password!).label : '—';
      jsonParts.add('{"id":"${e.id}","name":"${e.name}","username":"${e.username ?? ''}","strength":"$s"}');
      lines.add('• ${e.name}${e.username != null ? ' (${e.username})' : ''} [ID: ${e.id}]');
    }

    return ToolResult(
      toolName: definition.name,
      parameters: p,
      result: '{"found": [${jsonParts.join(',')}]}',
      displayText: '🔐 ${results.length} Eintrag(e) gefunden:\n${lines.join('\n')}',
    );
  }

  Future<ToolResult> _get(Map<String, dynamic> p) async {
    final id = p['id'] as String?;
    if (id == null || id.isEmpty) {
      return ToolResult(
        toolName: definition.name,
        parameters: p,
        result: '{"error": "id required for get"}',
        displayText: '❌ ID fehlt',
        isError: true,
      );
    }
    final entry = await passwordService!.getEntry(id);
    if (entry == null) {
      return ToolResult(
        toolName: definition.name,
        parameters: p,
        result: '{"error": "not found"}',
        displayText: '❌ Eintrag nicht gefunden',
        isError: true,
      );
    }
    final strength = entry.password != null ? PasswordService.checkStrength(entry.password!).label : '—';

    return ToolResult(
      toolName: definition.name,
      parameters: p,
      result:
          '{"id":"${entry.id}","name":"${entry.name}","username":"${entry.username ?? ''}","url":"${entry.url ?? ''}","notes":"${entry.notes ?? ''}","strength":"$strength"}',
      displayText:
          '🔐 ${entry.name}\n'
          '${entry.username != null ? '👤 ${entry.username}\n' : ''}'
          '${entry.url != null ? '🔗 ${entry.url}\n' : ''}'
          '${entry.notes != null ? '📝 ${entry.notes}\n' : ''}'
          'Stärke: $strength',
    );
  }

  Future<ToolResult> _delete(Map<String, dynamic> p) async {
    final id = p['id'] as String?;
    if (id == null || id.isEmpty) {
      return ToolResult(
        toolName: definition.name,
        parameters: p,
        result: '{"error": "id required for delete"}',
        displayText: '❌ ID fehlt',
        isError: true,
      );
    }
    final ok = await passwordService!.deleteEntry(id);
    return ToolResult(
      toolName: definition.name,
      parameters: p,
      result: '{"deleted": $ok}',
      displayText: ok ? '✅ Passwort-Eintrag geloescht' : '❌ Eintrag nicht gefunden',
    );
  }

  ToolResult _generate(Map<String, dynamic> p) {
    final length = (p['length'] as int?)?.clamp(6, 128) ?? 20;
    final pw = PasswordService.generatePassword(length: length);
    final strength = PasswordService.checkStrength(pw);

    return ToolResult(
      toolName: definition.name,
      parameters: p,
      result: '{"password": "$pw", "length": $length, "strength": "${strength.label}"}',
      displayText:
          '🔑 Passwort generiert ($length Zeichen).\n'
          '**Loesch diese Nachricht manuell!**\n'
          'Stärke: ${strength.label}',
    );
  }

  Future<ToolResult> _list() async {
    final entries = await passwordService!.listEntries();
    if (entries.isEmpty) {
      return ToolResult(
        toolName: definition.name,
        parameters: const <String, dynamic>{},
        result: '{"entries": []}',
        displayText: '📭 Keine Passwoerter gespeichert',
      );
    }

    final jsonParts = <String>[];
    final lines = <String>[];
    for (final e in entries) {
      final s = e.password != null ? PasswordService.checkStrength(e.password!).label : '—';
      jsonParts.add('{"id":"${e.id}","name":"${e.name}","username":"${e.username ?? ''}","strength":"$s"}');
      lines.add('• ${e.name}${e.username != null ? ' (${e.username})' : ''} [ID: ${e.id}]');
    }

    return ToolResult(
      toolName: definition.name,
      parameters: const <String, dynamic>{},
      result: '{"entries": [${jsonParts.join(',')}]}',
      displayText: '🔐 ${entries.length} Passwort(e):\n${lines.join('\n')}',
    );
  }
}
